### ISSUE TITLE
Better styling of background/containers

### ISSUE THREAD

**Issue by tan8325** [tan8325/Team4_DiceGame_Repo#1]
Make the background and containers look better.

Current look:
![image](https://github.com/tan8325/Team4_DiceGame_Repo/assets/58007188/aa22e7ff-d949-46c8-925d-1c0cb33e5be6)

**Comment by andz138** [comment]
Should we aim for a casino-type background or sort of like a board-game background?

**Comment by andz138** [comment]
I'll be working on the background/containers
