### ISSUE TITLE
Find a hack/workaround for previous siblings in CSS to hide certain elements.

### ISSUE THREAD

**Issue by tan8325** [tan8325/Team4_DiceGame_Repo#2]
https://stackoverflow.com/questions/1817792/is-there-a-previous-sibling-selector

Example below: We want to hide dice1 when we are on page #dice2

![image](https://github.com/tan8325/Team4_DiceGame_Repo/assets/58007188/62a4c908-cc4b-456a-b4a7-cd3fed3ecf99)

**Comment by techlifedfmg** [comment]
I'll be working on this
