### ISSUE TITLE
Find team name

### ISSUE THREAD

**Issue by tan8325** [tan8325/Team4_DiceGame_Repo#7]
We need a team name for the project. Please come up with some so everyone can vote on them.

**Comment by andz138** [comment]
How serious is the name supposed to be? What about the Code & Craps Collective?

**Comment by tan8325** [comment]
> How serious is the name supposed to be? What about the Code & Craps Collective?

Doesn't have to be serious. Are you referring the card game craps? Code Rollers might be a good one.

**Comment by andz138** [comment]
> > How serious is the name supposed to be? What about the Code & Craps Collective?
> 
> Are you referring the card game craps? Code Rollers might be a good one.

Yes, I was. I like Code Rollers too, let's roll with that.
